import { describe, expect, it } from "vitest";
import { classifyPath, decodeText, looksGenerated, notebookToText } from "@/lib/ingest/filters";

const reason = (path: string, size = 100) => {
  const v = classifyPath(path, size);
  return v.keep ? "keep" : v.reason;
};

describe("classifyPath", () => {
  it("keeps ordinary source and config", () => {
    for (const p of ["src/index.ts", "app/page.tsx", "main.go", "bin/cli.js", "pkg/server/server.go", "package.json", ".env.example", "Dockerfile"]) {
      expect(reason(p)).toBe("keep");
    }
  });

  it("skips dependencies, build output and caches by folder", () => {
    expect(classifyPath("node_modules/react/index.js", 10)).toMatchObject({ keep: false, reason: "dependencies", dirDepth: 0 });
    expect(classifyPath("web/dist/app.js", 10)).toMatchObject({ keep: false, reason: "build-output", dirDepth: 1 });
    expect(reason("pkg/__pycache__/x.pyc")).toBe("cache");
    expect(reason(".next/server/page.js")).toBe("build-output");
  });

  it("skips lockfiles, assets, binaries and likely secrets", () => {
    expect(reason("package-lock.json")).toBe("lockfile");
    expect(reason("apps/web/pnpm-lock.yaml")).toBe("lockfile");
    expect(reason("public/logo.svg")).toBe("asset");
    expect(reason("fonts/Inter.woff2")).toBe("asset");
    expect(reason("tools/app.exe")).toBe("binary");
    expect(reason(".env")).toBe("secret");
    expect(reason(".env.local")).toBe("secret");
    expect(reason("certs/server.pem")).toBe("secret");
  });

  it("skips generated, empty and oversized files", () => {
    expect(reason("static/app.min.js")).toBe("generated");
    expect(reason("static/app.js.map")).toBe("generated");
    expect(reason("next-env.d.ts")).toBe("generated");
    expect(reason("src/empty.ts", 0)).toBe("empty");
    expect(reason("src/huge.ts", 500_000)).toBe("too-large");
    expect(reason("data/dump.json", 500_000)).toBe("data");
    expect(reason("LICENSE")).toBe("housekeeping");
    expect(reason(".github/ISSUE_TEMPLATE/bug.yml")).toBe("housekeeping");
  });
});

describe("decodeText", () => {
  it("rejects binary and normalises line endings", () => {
    expect(decodeText(new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x00, 0x01]))).toBeNull();
    expect(decodeText(new TextEncoder().encode("﻿a\r\nb\rc"))).toBe("a\nb\nc");
  });
});

describe("looksGenerated", () => {
  it("spots banners and minified code", () => {
    expect(looksGenerated("gen.ts", "// Code generated by protoc. DO NOT EDIT.\nexport {}")).toBe(true);
    expect(looksGenerated("api.ts", "/* eslint-disable */\n// This file was automatically generated by openapi-typescript.\n")).toBe(true);
    expect(looksGenerated("a.js", "x".repeat(5000))).toBe(true);
    expect(looksGenerated("a.ts", "export const a = 1;\n")).toBe(false);
  });

  it("keeps hand-written files that merely mention generated things", () => {
    expect(looksGenerated("schema.ts", "// Every table uses an auto-generated UUID as its primary key.\nexport const users = 1;")).toBe(false);
    expect(looksGenerated("config.ts", "// Do not edit these values without updating the docs.\nexport const a = 1;")).toBe(false);
  });
});

describe("notebookToText", () => {
  it("keeps cell sources and drops outputs", () => {
    const nb = JSON.stringify({
      cells: [
        { cell_type: "markdown", source: ["# Title"] },
        { cell_type: "code", source: "print(1)", outputs: [{ text: "1" }] },
      ],
    });
    const text = notebookToText(nb)!;
    expect(text).toContain("print(1)");
    expect(text).toContain("# # Title");
    expect(text).not.toContain('"outputs"');
  });
});
